config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :posts do
    resources :comments
  end
  
  root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
    has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    
def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(params[:comment].permit(:name, :body))
    redirect_to post_path(@post)
end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
      @posts = Post.all.order("created_at DESC")
  end

  def new
      @post = Post.new
  end
  
  
  

  def create
      @post = Post.new(post_params)

      if @post.save
          redirect_to @post
      else
          render 'new'
      end
  end
  
  
  
  
  

  def show
      @post = Post.find(params[:id])
      @comments = @post.comments
     
  end
  
  
  
  
  

  def update
      @post = Post.find(params[:id])

      if @post.update(post_params)
          redirect_to @post
      else
          render 'edit'
      end
  end



  def destroy
      @post = Post.find(params[:id])
      @post.destroy

      redirect_to posts_path

  end

  private

  def post_params
      params.require(:post).permit(:title, :content)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<strong><%= comment.name %> </strong> <br>
<%= comment.body %> <br>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
<p>
    
    <%= f.label :name %> <br>
    <%= f.text_field :name %>
</p>
<p>
    
<%= f.label :body %> <br>
<%= f.text_area :body %>
</p>
<p>
    
    <%= f.submit %>
</p>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hunters Food Recipe Page</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <section class="hero is-danger is-medium">
      <div class="hero-head has-background-grey-dark">
        <nav class="navbar has-background-grey-dark">
          <div class="container">
            <div class="navbar-brand ">
              <%= link_to 'Pizza Discussion Board', root_path, class: "navbar-item" %>
              <span class="navbar-burger" data-target="navbarMenuHeroA">
                <span></span>
                <span></span>
                <span></span>
              </span>
            </div>
            <div id="navbarMenuHeroB" class="navbar-menu ">
              <div class="navbar-end">
                <%= link_to "New Pizza Topic", new_post_path, class:"navbar-item" %>
              </div>
            </div>
          </div>
        </nav>
      </div>

      <div class="hero-body">
        <div class="container has-text-centered">
          <h1 class="title">
            <%= yield :page_title %>
          </h1>
        </div>
      </div>
    </section>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<%content_for :page_title, "Pizza Orders" %>
<h1 class="title">Pizza Talk</h1>
<section class="section">
    <% @posts.each do |post| %>
    <div class ="card">
        <div class="card-content">
            <div class="media">
                <div class="media-content">
                    <p class="title is-4"> <%= link_to post.title, post %> </p>
                </div>
            </div>
            <div class="content">
                <%= post.content %>
            </div>
            <div class="comment-count">
                <span class="tag is-rounded"><%# comment count%></span>
            </div>
        </div>
    </div>
    <% end %>
</section>

app/views/posts/new.html.erb
<%content_for :page_title, "New Pizza Discussion" %>
<h1 class="title"> Topping Suggestion</h1>

<div class="section">
    <%= simple_form_for @post do |f| %>
    <div class="field">
        <div class="control">
            <%= f.input :title, input_html: { class: "input" }, wrapper:false, label_html: {class:'label'} %>
            
        </div>
    </div>
    <% end %>
</div>
<div class="field">
    <%= simple_form_for @post do |f| %>
    <div class="field">
        <div class="control">
            <%= f.input :content, input_html: { class: "textarea" }, wrapper:false, label_html: {class:'label'} %>
            
        </div>
    </div>
    <%= f.button :submit, 'Post Pizza Topic', class: "button is-danger" %>
    <% end %>
</div>

app/views/posts/show.html.erb
<% content_for :page_title, @post.title %>

<section class="section">
    <div class="container">
        <nav class="level">
       
          <div class="level-left">
            <p class="level-item">
                <strong>Actions</strong>
            </p>
          </div>
 
              <p class="level-item">
                <%= link_to "Delete", post_path(@post), method: :delete, data: { confirm: "Are you sure?" }, class:"button is-grey" %>
                </p>
          </div>
        </nav>
        <hr/>

        <div class="content">
            <%= @post.content %>
        </div>
    </div>
    <div>
 <h2><%= render "comments/form" %>  <strong>Comments</strong> <br>

<%= render @post.comments %> <br> <br> <br>  </h2>
 
</div>

</section>